create or replace PROCEDURE upd_isolation
IS
BEGIN
  IF TO_CHAR (SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR (SYSDATE, 'DY') IN ('SAT', 'SUN') THEN


    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    DBMS_OUTPUT.PUT_LINE('LEVEL SERIALIZABLE');


  ELSE

    SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    DBMS_OUTPUT.PUT_LINE('READ COMMITTED');


  END IF;
END upd_isolation;